spring:   
  application:
    name: application-client
  profiles:
    active: dev
security:  
  basic:  
    enabled: true    #启用SpringSecurity的安全配置项  
  user:  
    name: chentao    #认证用户名  
    password: chentao #认证密码  
    #role:              #授权角色

management:
  security:
    enabled: false
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://203.195.163.69:1110}/eureka/
