spring:   
  application:
    name: application-client
  profiles:
    active: dev
  cloud:
    bus:
     trace:
      enabled: true
  rabbitmq:
    host: 203.195.163.69
    port: 5672
    username: chentao
    password: chentao

management:
  security:
    enabled: false
