spring:   
  application:
    name: application-client
  profiles:
    active: dev
  rabbitmq:
    host: 203.195.163.69
    port: 5672
    username: chentao
    password: chentao


management:
  security:
    enabled: false
    
#eureka:
  #client:
    #registryFetchIntervalSeconds: 5
    #serviceUrl:
      #defaultZone: ${EUREKA_SERVICE_URL:http://203.195.163.69:1110}/eureka/
